Ahmad Akbar
rmt-08-helsinki-fox/fancy-todo pull request #36
Opened 2021-02-01 15:23 UTC by ahmad-akbar

- [ ] user register
- [ ] user login
- [ ] create todo
- [ ] update todo
- [ ] findOne todo
- [ ] delete todo
- [ ] error handling

2021-02-02 02:46 UTC, mhmmd-ysf requested changes
Overall udah ok
Good Job!

2021-02-02 02:46 UTC, mhmmd-ysf commented on server/controller/todoController.js
> +const { todo } = require('../models/index')
Biasain nama model pake `PascalCase`

2021-02-02 02:46 UTC, mhmmd-ysf commented on server/controller/todoController.js
> +          res.status(200).json(dataTodo[1][0])
kalo udah ada error handler semuanya dipindah ke next

2021-02-02 02:46 UTC, mhmmd-ysf commented on server/migrations/20210201061446-create-todo.js
> +      // },
Ini kenapa dikomen?

2021-02-02 14:47 UTC, ahmad-akbar commented on server/controller/todoController.js
> +const { todo } = require('../models/index')
sudah saya perbaiki kak

2021-02-02 14:47 UTC, ahmad-akbar commented on server/controller/todoController.js
> +          res.status(200).json(dataTodo[1][0])
udah pindah semua di error handler kak

2021-02-02 14:50 UTC, ahmad-akbar commented on server/migrations/20210201061446-create-todo.js
> +      // },
tadi malam mau rencananya kerja auth. nah UserId ini kan dibutuhin ketika create todo dan UserId ini diambil dari Authnya. Tapi belum sempat dikerjain. jadi saya komen saja dulu diimgrasi biar tidak ikut dicreate kolomnya di table todo.

2021-02-03 06:18 UTC, mhmmd-ysf requested changes
Overall udah oke, udah bisa lanjut client ini
Good Job!

2021-02-03 06:18 UTC, mhmmd-ysf commented on server/controller/weatherController.js
> +    const weather = `http://api.weatherstack.com/current?access_key=${process.env.WEATHER_API_KEY}&query=Makassar`
Ini makassar aja?

2021-02-03 06:48 UTC, ahmad-akbar commented on server/controller/weatherController.js
> +    const weather = `http://api.weatherstack.com/current?access_key=${process.env.WEATHER_API_KEY}&query=Makassar`
iya kak. Dari 3rd party api nya yang saya baca, hanya bisa mengambil 1 titik lokasi saja

2021-02-05 05:55 UTC, mhmmd-ysf requested changes
Overall udah ok, cuma migrationnya aja yang lumayan aneh coba benerin ya

2021-02-05 05:55 UTC, mhmmd-ysf commented on server/models/todo.js
> +    }
Gua baru ngeh ini tambahan di tengah ya, jangan kaya begini kalo emang perlu bikin ulang migrationnya

2021-02-06 10:59 UTC, ahmad-akbar commented on server/models/todo.js
> +    }
udah saya bikin ulang migration nya kak

2021-02-08 07:59 UTC, mhmmd-ysf reviewed
Overall udah oke, weather api baru di server aja ya, tapi nice juga ada fitur search.
Good Job!

2021-02-08 07:59 UTC, mhmmd-ysf commented on client/index.html
> +        <input type="submit" class="btn btn-outline-danger" onclick="checkAuth()" value="Cancel">`
Kelebihan
```suggestion
        <input type="submit" class="btn btn-outline-success" onclick="addTodo()" value="Add Todo">
        <input type="submit" class="btn btn-outline-danger" onclick="checkAuth()" value="Cancel">
```

2021-02-08 07:59 UTC, mhmmd-ysf commented on client/main.js
> +              <input class="form-control" type="text" value="Not Done" id="updateTodo-Status" aria-label="Disabled input example" disabled>
Mungkin ini kebawa dari create ya yang belom boleh dibikin done
```suggestion
              <input class="form-control" type="text" value="Not Done" id="updateTodo-Status" aria-label="Disabled input example">
```

2021-02-08 07:59 UTC, closed without merging