REST API TASK
rmt-08-helsinki-fox/fancy-todo pull request #38
Opened 2021-02-01 15:38 UTC by rizkicaandra

TASK 02-REST-API
Rest api documentation is not done yet..

2021-02-02 00:51 UTC, rizkicaandra commented
Api doc sudah di commit..

2021-02-02 02:37 UTC, mhmmd-ysf requested changes
Overall udah ok, tinggal API Doc nya diupdate lagi bareng sama fitur register sama login ok.
Good Job!

2021-02-03 07:12 UTC, mhmmd-ysf requested changes
Overall udah ok

2021-02-03 07:12 UTC, mhmmd-ysf commented on server/api-doc.md
> +    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJyaXpraUBlY2FtcHV6LmNvbSIsImlhdCI6MTYxMjMxMTkwN30.4HCGps4hzqZ7GJf4qqKl2Rs7RCq4ppANw6mqSqFhUSs"
Contoh token jangan pake token asli
```suggestion
    "accessToken": "<token>"
```

2021-02-03 07:12 UTC, mhmmd-ysf commented on server/middlewares/authenticate.js
> +      const decoded = jwt.verify(token, process.env.SECRET )
verify pindahin ke helpers juga
```suggestion
const verify = require('../helpers/jwt')

const authenticate = (req, res, next) => {
    try{
      const token = req.headers.token
      const decoded = verify(token, process.env.SECRET)
```

2021-02-03 07:12 UTC, mhmmd-ysf commented on server/middlewares/authorize.js
> +        }
kalo nggak ada todo, throw nya 2x, coba benerin alur if nya

2021-02-05 04:33 UTC, mhmmd-ysf requested changes
Overall udah oke fungsionalitasnya, tinggal perbaiki create nya ya

2021-02-05 04:33 UTC, mhmmd-ysf commented on server/app.js
> +if(process.env.NODE_ENV != 'development'){
ENV itu justru dipake ketika env == 'development' bukan kebalik

2021-02-05 04:33 UTC, mhmmd-ysf commented on client/index.html
> +            <th>Title</th>
Kepala kolomnya 3...

2021-02-05 04:33 UTC, mhmmd-ysf commented on client/script.js
> +            <td>${element.title}</td>
...tapi isinya punya 4 kolom

2021-02-05 04:33 UTC, mhmmd-ysf commented on client/script.js
> +            <td>${element.title}</td>
dan pilihannya baru delete ya, belom ada update nya

2021-02-06 10:36 UTC, rizkicaandra commented
env :
SECRET=ronaldo
GOOGLE_CLIENT_ID=726832526892-1hlgccen4skgh3a5vd20ntqdetspqqg5.apps.googleusercontent.com

Fitur:
tidak ada fitur tambahakn selain fitur utama..
Kendala :
saya mengalami kendala di bagian front end untuk mengatur kapan suatu element tampil dan ketika element lain harus dihide..

2021-02-08 07:05 UTC, mhmmd-ysf commented
Overall udah ok, cuma googlenya nggak jalan karena default URI-nya nggak terdaftar (localhost:3000), kalo pake host yang beda daftarin aja semuanya, yang kamu pake sama yang default. Terus di API docs, kok nggak ada error 401? padahal di codenya ada error 401. Sama clientnya masih FKRK ya (Font Koran, Rata Kiri) next time dilatih seni desain web nya dengan pake css / css framework biar web nya lebih ✨aesthetic✨ ok
Good Job!

2021-02-08 07:05 UTC, closed without merging