CRUD Todo
rmt-08-helsinki-fox/fancy-todo pull request #53
Opened 2021-02-01 18:33 UTC by Adhann

task Api Doc unfinished

2021-02-02 02:12 UTC, mhmmd-ysf requested changes
API Doc, register login belum ya

2021-02-02 02:12 UTC, mhmmd-ysf commented on server/controllers/todosController.js
> +    if (!id) { res.status(400).json({ error: 'Invalid Input'}) }
jangan 1 line
```suggestion
    if (!id) {
      res.status(400).json({ error: 'Invalid Input'})
    }
```

2021-02-03 06:44 UTC, mhmmd-ysf requested changes
API doc masih belum ya

2021-02-03 06:44 UTC, mhmmd-ysf commented on server/controllers/todosController.js
>        res.status(500).json(err)
ini belom next

2021-02-03 06:44 UTC, mhmmd-ysf commented on server/middlewares/authentication.js
> +    const decoded = jwt.verify(token, process.env.SECRET)
ini pindahin ke helpers
```suggestion
const verify = require('../helpers/jwt').verify

const authentication = function (req, res, next) {
  try {
    const token = req.headers.token
    const decoded = verify(token, process.env.SECRET)
```

2021-02-03 06:44 UTC, mhmmd-ysf commented on server/middlewares/authentication.js
> +    })
belom next

2021-02-03 12:46 UTC, Adhann commented on server/controllers/todosController.js
>        res.status(500).json(err)
done

2021-02-03 12:46 UTC, Adhann commented on server/middlewares/authentication.js
> +    const decoded = jwt.verify(token, process.env.SECRET)
done

2021-02-04 01:52 UTC, Adhann commented on server/middlewares/authentication.js
> +    })
done

2021-02-05 03:37 UTC, mhmmd-ysf requested changes
Ada poin-poin yang perlu diliat:
- register nge-axios 2x
- value status ketika edit nggak kepopulate
- value date juga nggak ngubah ketika edit

Tapi overall udah ok

2021-02-05 03:37 UTC, mhmmd-ysf commented on client/assets/js/main.js
> +    $(document).ready(() => {
Ini agak aneh sih kenapa semuanya dimajuin 1 tab?

2021-02-05 03:37 UTC, mhmmd-ysf commented on client/assets/js/main.js
> +                <h5 class="modal-title">Modal ${el.title}</h5>
mungkin typo
```
                <h5 class="modal-title">Modal ${todo.title}</h5>
```

2021-02-08 07:29 UTC, mhmmd-ysf reviewed
Overall udah bagus.
Good Job!

2021-02-08 07:29 UTC, mhmmd-ysf commented on server/API-doc.md
> +        "data": [
bisa disingkat:
```
"data": [
  <weather_data>
]
```

2021-02-08 07:29 UTC, mhmmd-ysf commented on client/assets/js/main.js
> +        $("#weather").append(`
Biasain empty dulu sebelum diisi apa-apa biar nggak numpuk ketika fetch nya ke-trigger lagi

2021-02-08 07:30 UTC, closed without merging