CRUD
rmt-08-helsinki-fox/fancy-todo pull request #54
Opened 2021-02-01 19:54 UTC by AwangMedidat

2021-02-02 02:09 UTC, mhmmd-ysf reviewed
Register login masih belum ya
env
SECRET=hektip
GAPI=gugle
APIKEY=9384bf5893247f

2021-02-02 02:09 UTC, mhmmd-ysf commented on server/controller/TodoController.js
> +                if (err.errors.length > 0) {
pastikan `err` akan selalu punya properti `errors` nggak, kalo nggak ada ini bisa error

2021-02-02 02:10 UTC, mhmmd-ysf commented
API Documentation juga belom ada ya

2021-02-03 06:30 UTC, mhmmd-ysf requested changes
Overall udah ok

2021-02-03 06:30 UTC, mhmmd-ysf commented on server/middleware/authencicate.js
> +        const decoded = jwt.verify(token,process.env.SECRET)
JWT definisiin di helpers
```suggestion
const verify = require('../helpers/jwt').verify

const authencicate = function (req,res,next) {
    try{
        const token = req.headers.token
        const decoded = verify(token,process.env.SECRET)
```

2021-02-08 06:02 UTC, mhmmd-ysf reviewed
client update belom selesai ya, URI default (localhost:8080) juga nggak kedaftar jadi nggak bisa cek google, dan masih ada yang hard reload ya, jadi belum SPA, dan ini penaltinya lumayan gede.
Tapi overall masih ok, good job!

2021-02-08 06:02 UTC, mhmmd-ysf commented on server/API-doc.md
> +    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJhd2FuZ21lZGlkYXQ2NUBnbWFpbC5jb20iLCJpYXQiOjE2MTI1OTc2ODh9.Ebb8eCYUImbgEyX7otmtYlVduuBCriffjJIr4iBe8Yc"
jangan dikasih contoh juga dong, kalo gitu buat apa ada line 131

2021-02-08 06:02 UTC, mhmmd-ysf commented on server/controller/UserController.js
> +            password : user.password
gua baru ngeh ini register kenapa balikin password juga?

2021-02-08 06:02 UTC, mhmmd-ysf commented
Sama biasain jangan ngerjain client di template ya

2021-02-25 22:20 UTC, AwangMedidat commented
Fancy Todo

2021-02-26 06:50 UTC, mhmmd-ysf commented
Good Job!

2021-02-26 06:50 UTC, closed without merging